server:
   port: 7071


eureka:
   client:
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:7070/eureka/

spring:
   application:
      name: gateway-service
   cloud:
      gateway:
         routes:
         -  id: employee-service
            uri: http://localhost:7072/
            predicates:
            - Path=/employee/**